---
# tasks file for prometheus

- name: Disable firewalld
  become: yes
  systemd:
    name: firewalld
    state: stopped
  when: ansible_os_family == "RedHat"

- name: create prometheus system group
  become: yes
  group:
    name: prometheus
    system: true
    state: present

- name: Create user Prometheus
  become: yes
  user:
    name: "{{ prometheus_user }}"
    createhome: "{{ create_home }}"
    state: present
    system: yes

- name: Create prometheus directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0755
  with_items:
    - "{{ path_exec_prometheus }}"
    - "{{ path_conf_prometheus }}"
    - "{{ path_conf_node }}"

- name: Get prometheus
  become: yes
  unarchive:
    src: "{{ download_prometheus }}"
    dest: "/tmp/"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    remote_src: yes

- name: cp prometheus and promtool binaries
  become: yes
  copy:
    src: "/tmp/{{ prometheus_folder }}/{{ item }}"
    dest: "{{ path_exec_prometheus }}"
    mode: 0755
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    remote_src: yes
  with_items:
    - prometheus
    - promtool

- name: Create conf node exporter
  become: yes
  template:
    src: node.j2
    dest: "{{ path_conf_node }}/{{ item.host }}.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
  with_items: "{{ node_exporter }}"

- name: Create systemd
  become: yes
  template:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_user }}"
    mode: 0755
  with_items:
    - {file: prometheus.yml.j2, dest: "{{ path_conf_prometheus }}prometheus.yml" }

- name: Create systemd
  become: yes
  template:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - {file: prometheus.service.j2, dest: /etc/systemd/system/prometheus.service}

- name: Start service
  become: yes
  systemd:
    name: prometheus
    state: started
    daemon_reload: yes
