---
# tasks file for prometheus

- name: Disable firewalld
  become: yes
  systemd:
    name: firewalld
    state: stopped
  when: ansible_os_family == "RedHat"

- name: Create user Prometheus
  become: yes
  user:
    name: "{{ prometheus_user }}"
    createhome: "{{ create_home }}"
    state: present

- name: Create folder
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    mode: 440
  with_items:
    - "{{ path_exec_prometheus }}"
    - "{{ path_conf_prometheus }}"
 
- name: Get prometheus
  become: yes
  unarchive:
    src: "{{ download_prometheus }}"
    dest: "{{ path_exec_prometheus }}"
    owner: "{{ prometheus_user }}"
    remote_src: yes

- name: Create systemd
  become: yes
  template:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}" 
    owner: "{{ prometheus_user }}"
  with_items:
    - {file: prometheus.service.j2, dest: /etc/systemd/system/prometheus.service}
    - {file: prometheus.yml.j2, dest: "{{ path_conf_prometheus }}prometheus.yml" }    

- name: Start service
  become: yes
#  become_user: "{{ prometheus_user }}"
  systemd:
    name: prometheus
    state: started
    daemon_reload: yes
